pipeline{
    agent any
    environment {
        def myString = "Hello World"
        def myNumber = 10
        def myBool = false
    }

    stages{
        stage("Demo"){
            steps{
                echo "  my String: ${myString}"
                echo "  my myNumber: ${myNumber}"
                echo "  my myBool: ${myBool}"
            }
        }
    }
}