pipeline{
    agent any
    parameters{
        string(defaultValue:"TEST", description:"Which environment to deploy in?",name:"deployENV")
    }

    stages{
        stage("Demo"){
            steps{
                echo "booleanParam is set to: ${params.deployENV}"
            }
        }
    }
}